[theme]

# The preset Streamlit theme that your custom theme inherits from.
# This can be one of the following: "light" or "dark".
base = "dark"

# Primary accent color.
primaryColor = "#295C90"

# Background color of the app.
backgroundColor = "#FAFAFA"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#262730"

textColor = "#FAFAFA"
